graph LR
    Origin -->|Physical| Humans
    Origin -->|Magical| Independent?

    Independent? -->|Yes| Affinity[Magic Affinity]
    Independent? -->|No| Host[Type of Host]

    Affinity -->|Superior| Gods
    Affinity -->|Ordinary| Elves
    Affinity -->|Inferior| Beastfolk

    Host -->|Humans| Demonfolk
    Host -->|Animals| Demonbeasts[Demon Beasts]
